### ISSUE TITLE
Box & whisker plots for log success (from Cohn paper)

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#6]
#### Description

Create box & whisker plot for each role (or, at least a few) for log success values to verify there's enough variance.

#### To-do

- [x] (locally) calculate log success for each user info in each follower range for each role (should be able to copy/paste code from other file)
- [x] (locally) plot in box/whisker
- [x] edit .sh files for running on grid
- [ ] run on grid
- [ ] copy pngs from grid to local

**Comment by bellecarrell** [comment]
something with the python environment not recognizing tweepy. will check in a bit

**Comment by bellecarrell** [comment]
going to fix later.. copying some of files to local to get intermediate results
