### ISSUE TITLE
hits on dirk's account

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#64]
- [x] create HIT html (#43 )

- [x] script for grabbing top n user sample (and pointing to top of "unused" blogger set) (#65)

- [x] script for generating HIT CSV (#66)

- [x] generate 100 user pre-study CSV

- [x] run pre-study (#55)

- [x] analyze pre-study results (#68)

- [x] pre-study followup (#69)

- [x] generate full study CSV

- [ ] run full study

**Comment by bellecarrell** [comment]
discussing pre-study with @abenton on gchat:
"i added my hit csv to the repo
it currently has 100 users bc we have 11 intervals instead of 10
i must have miscounted?
so we can either roll with 110 users at 10 per interval, come up with new intervals and rerun, or something else"
